language: go
sudo: false

matrix:
  include:
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: tip
  allow_failures:
    - go: tip

install:
  - # Skip
script:
  - go get -t -v ./...
  - go test
